name: Publish

on:
  push:
    branches: [ main ]
    paths:
      - 'sources/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore MapperDSLNugetPack.sln
    - name: Build
      run: dotnet build --no-restore -c Release MapperDSLNugetPack.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release MapperDSLNugetPack.sln
    - name: Pack
      run: dotnet pack --no-restore -c Release -o output MapperDSLNugetPack.sln
    - name: Publish package
      run: dotnet nuget push output/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
